name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Setup Backend Environment
        working-directory: ./backend
        run: |
          echo "MONGODB_URI=mongodb://localhost:27017/test" > .env
          echo "JWT_SECRET=test-secret" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm run test:ci
        env:
          CI: true
          NODE_ENV: test

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test:ci
        env:
          CI: true

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        if: success()
        with:
          files: |
            ./backend/coverage/lcov.info
            ./frontend/coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
